<a href="https://colab.research.google.com/github/Lotfullah21/Tensors_/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
Basically Tensors are the main data strucuture of machine learning operatins,while adding new layers into the network there is going to be so many operations on tensors. if we consider one of the operations which happens in a layers,  this one layer wiht 128 neurons **tf.keras.layers.Dense(128,activation = 'relu')**.              
**output = relu(dot(w,input)+b)**
                      if we look at the ouput deeper, there is three operations happening.
1. Dot product between the weights and the neurons.
2. after Dot prodcut we do addition operation with bias(b).
3. at the end as we are using the relu activatin function, we apply this function which returns max(0,X).


# 1 Element Wise opeartion:
the relu and the addition operation are element wise operation, it means all the elements will be involeved in the operation and the opeartion goes on individually to each of them.

In [76]:
import numpy as np
def relu_operation(x):
  assert len(x.shape)==2
  # assertion to check the shape should be equll to 2(2D tensor), else raise error
  x = x.copy()
  # it creates a shallow coppy of x
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      # relu max(0,x)
      x[i,j] = max(x[i,j],0)
  return x     
relu_operation(np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]))


array([[ 2.,  0.,  2., 12., 12.],
       [ 2.,  0.,  2., 12., 12.],
       [ 0.,  0.,  0., 12., 12.]])

# Addition

In [77]:
def addition(x,y):
  assert len(x.shape)==2
  assert x.shape == y.shape
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = x[i,j]+y[i,j]
  return x
addition(np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]),np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]))  

array([[  4.  , -46.  ,   4.  ,  24.  ,  24.  ],
       [  4.  ,  -2.  ,   4.  ,  24.  ,  24.  ],
       [ -2.  ,  -2.  ,  -0.86,  24.  ,  24.  ]])

# Multiplication

In [78]:
def Mul(x,y):
  assert len(x.shape)==2
  assert x.shape == y.shape

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = x[i,j]*y[i,j]
  return x
Mul(np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]),np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]))  

array([[4.000e+00, 5.290e+02, 4.000e+00, 1.440e+02, 1.440e+02],
       [4.000e+00, 1.000e+00, 4.000e+00, 1.440e+02, 1.440e+02],
       [1.000e+00, 1.000e+00, 1.849e-01, 1.440e+02, 1.440e+02]])


# Subtraction


In [79]:
def Subtraction(x,y):
  assert len(x.shape)==2
  # in matrices in order to do arithmetic operations, we need few conditions, but the generla one would be to expect both the matrices have smae lenght
  assert x.shape == y.shape

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = x[i,j]-y[i,j]
  return x
Subtraction(np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]),np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]))  

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Division

In [80]:
def Division(x,y):
  assert len(x.shape)==2
  assert x.shape == y.shape

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = x[i,j]/y[i,j]
  return x
Division(np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]),np.array([[2,-23,2,12,12],[2,-1,2,12,12],[-1,-1,-.43,12,12]]))  

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
# in this snip we can see how easy it is to do element wise operation using numpy
import numpy as np
x = np.array([[-2,13,1,2,1],[2,13,1,2,1],[2,13,1,2,1]])
y = np.array([[0,21,1,2,4],[-12,13,1,2,1],[-20,13,1,2,1]])
z = x+y
print("summation\n",z)
# by using maximum built_in function we did relu operation here.
w = np.maximum(z,0)
print("relu\n",w)
# max will return max element among the elements present in the matrices, it is different from maximum
s = np.max(z,0)
print("maximum numbers among elements in matrices\t\n",s)


summation
 [[ -2  34   2   4   5]
 [-10  26   2   4   2]
 [-18  26   2   4   2]]
relu
 [[ 0 34  2  4  5]
 [ 0 26  2  4  2]
 [ 0 26  2  4  2]]
maximum numbers among elements in matrices	
 [-2 34  2  4  5]


 in numpy we can do the above operations, but it could super fast and easy to implement.
 

# BroadCasting:
when we are adding two matrices, they should have same dimensions or shape, other wise the operation would not succeed, but in neural network, we are having vectors and matrices of different shapes, so how to overcome this issue?"
this is where the **broadcasting** comes in front, the smaller tensor will be broadcsted to match the shape of the larger one.
How this happens ?
1. Axis (called broadcast axes) are added to the smaller tensor to match the ndim of the larger tensor.
2. The smaller tensor is repeated along side this new axes to match the the full shape of the larger tensor.

for example if we have X in the shape of (63,10) and Y in the shape of (32,10), first we add an empty exes to Y, then we repeat Y 32 times alongside this new axis, so that to make the shape of Y (64,10).
this operation do not happen in memory level, because every time we have to add a new tensor and save it, which is costly for us in terms of memory and efficiency. the operation happens in algorithmic level and virtually.

In [82]:
def add(x,y):
  assert len(x.shape)==2
  assert len(y.shape)==1
  assert x.shape[1] == y.shape[0]
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j]  = x[i,j]+y[j]
  return x
x = np.array([[3,22,1],[10,20,-2]])
y = np.array([1,12,0])
add(x,y)

array([[ 4, 34,  1],
       [11, 32, -2]])

as we can see eventhough the y is 1D but still we are able to add to x by using the above code,
but still it is an efficient way, so lets try the another way.


In [83]:
x = np.array([[8,22,1],[21,10,1]])
y = np.array([2,1,0])
z = np.maximum(x,y)
z

array([[ 8, 22,  1],
       [21, 10,  1]])

In [84]:
x = np.random.random((2,4,3))
y = np.random.random((4,3))
z = np.maximum(x,y)
print('y=\t',y)
print('x\t',x)
print('z\t',z)

y=	 [[0.59955006 0.88520996 0.44160408]
 [0.82642287 0.45146039 0.99847546]
 [0.75521767 0.1502978  0.80314471]
 [0.78543381 0.18288199 0.13507801]]
x	 [[[0.8841385  0.67493843 0.9438241 ]
  [0.74146191 0.19532566 0.04399444]
  [0.185564   0.00710076 0.95032417]
  [0.98819543 0.03302502 0.94959284]]

 [[0.18627817 0.24003563 0.92584527]
  [0.90755023 0.76195207 0.16341637]
  [0.05609479 0.06710934 0.64603844]
  [0.34265935 0.93585823 0.1365639 ]]]
z	 [[[0.8841385  0.88520996 0.9438241 ]
  [0.82642287 0.45146039 0.99847546]
  [0.75521767 0.1502978  0.95032417]
  [0.98819543 0.18288199 0.94959284]]

 [[0.59955006 0.88520996 0.92584527]
  [0.90755023 0.76195207 0.99847546]
  [0.75521767 0.1502978  0.80314471]
  [0.78543381 0.93585823 0.1365639 ]]]


# Tensor dot
here after multuplyinge elements of a matrix,or a vector with each other we wills sum up them all.
we can multuply a vector by a matrix, the result will be a vector.


In [85]:
import numpy as np
x = [2,3,2]
y = [3,2,1]
z = np.dot(x,y)
z

14

In [86]:
def dot(x,y):
  # by specifiying the shape to be 1, we define it is a vector tensor
  assert len(x.shape)==1
  assert len(y.shape)==1
  assert x.shape[0]==y.shape[0]
  z = 0
  for i in range(x.shape[0]):
    z = z + x[i]*y[i]
  return z   
x = np.array([2,2,3])
y = np.array([2,1,1])
dot(x,y)

9

In [87]:
# Matrix with a vector
def dot(x,y):
  # by specifiying the shape to be 1, we define it is a vector tensor
  assert len(x.shape)==2
  assert len(y.shape)==1
  assert x.shape[1]==y.shape[0]
  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    for j in range(x.shape[0]):
      z[i] = z[i] + x[i,j]*y[j]
  return z   
x = np.array([[1,2,3],[1,3,1]])
y = np.array([8,1,4])
dot(x,y)

array([10., 11.])

In [88]:
x = np.array([[1,2,3],[1,3,1]])
y = np.array([8,1,4])
z = np.dot(x,y)
print(z)

[22 15]


# Tensor reshaping
reshaping a tensor means rearranging its rows and columns to match a target shape.

one useful case woudl be **transposition**, it is done in matrix to exchanges the rows with columns. 

In [89]:
# lets look at one example how the reshaping process takes place
x = np.array([[23,2,2,4],[34,2,2,3],[3,23,20,90]])
print(x.shape)
# while reshaping, remember that the product of rows and columns should be choosen as equall to original one
# for example,here we cannot choose reshape(6,3), because it has 18 elements and our x had 12.it can be (4,3),(6,2),(2,6),(12,1) and so on.
y = x.reshape(6,2)
y

(3, 4)


array([[23,  2],
       [ 2,  4],
       [34,  2],
       [ 2,  3],
       [ 3, 23],
       [20, 90]])

In [90]:
# Transpose
x = np.array([[32,2,1],[3,2,1]])

print('x\n',x)
print('shape\t',x.shape)

new_x = np.transpose(x)

print('new_x \n',new_x)
print('shape\t',new_x.shape)

x
 [[32  2  1]
 [ 3  2  1]]
shape	 (2, 3)
new_x 
 [[32  3]
 [ 2  2]
 [ 1  1]]
shape	 (3, 2)


In [112]:
A = [1,1,1,1]
np.linalg.norm(A)

2.0

In [4]:
import numpy as np
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    s = np.linalg.norm(A) + np.linalg.norm(B)
    return s
norm(np.random.rand(4,1),np.random.rand(4,1))


2.3373408489343883

In [63]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
   
    output = np.tanh(np.dot(weights.transpose(),inputs))
    return output
    #Your code here
    raise NotImplementedError
inputs = np.random.rand(2,1)
weights = np.random.rand(2,1)
print(weights.shape)
print(inputs.shape)
neural_network(inputs,weights)

(2, 1)
(2, 1)


array([[0.08763914]])

In [61]:
def neural_network(inputs, weights):
    o = np.matmul(weights.transpose(),inputs)
    return np.tanh(o)
    
    raise NotImplementedError
x = np.array([[2],[2]])
w = np.array([[3],[3]])

neural_network(x,w)


array([[1.]])

In [62]:
# implementing a simple neural network with the w weights and x inputs
def neural_network(inputs, weights):
    return  np.tanh(np.matmul(weights.transpose(),inputs))
    raise NotImplementedError
x = np.random.rand(2,1)
w = np.random.rand(2,1)


neural_network(x,w)

array([[0.29916839]])

# NOTE : the main source for this notebook would be Deep Learning with python,(by Francois chollet) and Machine learning course from MIT